### ISSUE TITLE
Unable to install the plugin via `nupm` on WSL

### ISSUE THREAD

**Issue by mohammadzainabbas** [fmotalleb/nu_plugin_desktop_notifications#6] opened 2024-07-30 13:31 UTC
Hi,

I'm trying to install this plugin on WSL using `nupm` but it's not working (see the error below):

![image](https://github.com/user-attachments/assets/f97f81d4-4354-49a7-807d-94e57dd1f1bc)

> [!IMPORTANT]
> I have tried to install it on the following WSL:
> 
> - [x] `Debian`
> - [x] `Ubuntu`
> - [x] `Kali-Linux`
> - [x] `Arch`

> [!NOTE]
> I have also tried the alternatives but `register` is no longer a valid `nushell` [command](https://www.nushell.sh/commands/).

**Comment by fmotalleb** [comment] 2024-07-30 15:11
I know what the issue is but I wont fix it I guess
 
well since its useless in WSL I don't think installing it on Nushell(inside WSL) is a good idea anyway
if you need this functionality on Windows using WSL install the plugin on the Windows's Nushell and then use `nu.exe -c "notify <args>"` inside the WSL
 I'll try using it inside WSL and if it works I will fix it

**Comment by fmotalleb** [comment] 2024-07-30 15:12
and for the register command
the new way is using `plugin add` to register a plugin I was too lazy too update the docs

**Closed as completed** 2024-08-07 20:35 UTC
